In [21]:
import sklearn
import torch
import torch.nn as nn
from torch.autograd import Variable
import torch.nn.functional as F
import numpy as np
import matplotlib.pyplot as plt
import torch.optim
from sklearn import datasets

x = torch.randn(3, requires_grad=True)
print(x)
y = x * 2
print(y)

z = y*y
print(z)

#backward要求根节点是个标量
z.backward()
#如果根节点是个张量，则需要使用雅可比
v = torch.tensor([1, 1, 1], dtype=torch.float)
z.backward(v)
#一般微分都是到最后的叶子节点，中间的非叶子节点是不会有梯度的
print(x.grad)

tensor([ 0.2394,  0.5996, -0.4761], requires_grad=True)
tensor([ 0.4789,  1.1992, -0.9522], grad_fn=<MulBackward0>)
tensor([0.2293, 1.4382, 0.9067], grad_fn=<MulBackward0>)
None
